name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Reemplaza con la versión de Python que estés utilizando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        id: pylint
        run: |
          pylint main.py > pylint_report.txt
          score=$(grep -o 'rated at [0-9.]\+/10' pylint_report.txt | awk '{print $3}')
          echo "score=${score}" >> $GITHUB_ENV

      - name: Upload Pylint report
        uses: actions/upload-artifact@v2
        with:
          name: pylint-report
          path: pylint_report.txt
